<?php
/**
 * Plugin Name: אוניברסיטת חיפה - אנשי סגל
 * Plugin URI: https://alternativ.co.il/plugins/haifa-staff-v2
 * Description: תוסף עצמאי לניהול ותצוגת רשימות סגל באתרי אוניברסיטת חיפה. ללא תלות ב-ACF.
 * Version: 2.0.98
 * Author: Benny Mozes, University of Haifa
 * Author URI: https://alternativ.co.il
 * Update URI: https://alternativ.co.il/plugins/haifa-staff-v2.json
 * License: GPL v2 or later
 * Text Domain: haifa-staff
 */

if ( ! defined( 'WPINC' ) ) { die; }

define('HAIFA_STAFF_V2_VERSION',    '2.0.98');
define('HAIFA_STAFF_V2_PLUGIN_DIR', plugin_dir_path(__FILE__));
define('HAIFA_STAFF_V2_PLUGIN_URL', plugin_dir_url(__FILE__));

// ── Faculty sites registry ────────────────────────────────────────────────────
// Single source of truth for all faculty sites in the university network.
// Key = site URL (trailing slash), Value = Hebrew display name.
define('HAIFA_STAFF_SITES', [
    'https://bennydev.haifa.ac.il/'         => 'בדיקה',
    'https://hevra.haifa.ac.il/'            => 'מדעי החברה',
    'https://cis.haifa.ac.il/'              => 'מדעי המחשב',
    'https://hw.haifa.ac.il/'               => 'מדעי הרווחה והבריאות',
    'https://med.haifa.ac.il/'              => 'רפואה',
    'https://edu.haifa.ac.il/'              => 'חינוך',
    'https://sciences.haifa.ac.il/'         => 'הפקולטה למדעים',
    'https://hcc.haifa.ac.il/'              => 'הפקולטה למדעי הרוח',
    'https://samc.haifa.ac.il/'             => 'בית הספר לארכיאולוגיה',
    'https://areahistory.haifa.ac.il/'      => 'בית הספר להיסטוריה אזורית',
    'https://arts.haifa.ac.il/'             => 'בית הספר לאמנויות',
    'https://marsci.haifa.ac.il/'           => 'בית הספר למדעי הים',
    'https://law.haifa.ac.il/'              => 'הפקולטה למשפטים',
]);

// ── WPML mu-plugin content ────────────────────────────────────────────────────
// This constant holds the exact content written to mu-plugins/haifa-staff-wpml-fix.php
// when the admin installs it from the settings page. Keep in sync with the live file.
define('HAIFA_STAFF_WPML_FIX_CONTENT', <<<'MUPLUGIN'
<?php
// Haifa Staff v2 — WPML compatibility fix
// Prevents WPML from intercepting /en/staff/ URLs before the plugin can handle them.
// Auto-generated by haifa-staff-v2. Do not edit manually.
$path = trim(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH), '/');
if (preg_match('#^en/staff(/([^/]+))?(/?)$#', $path, $matches)) {
    $_SERVER['HAIFA_STAFF_ORIGINAL_URI'] = $_SERVER['REQUEST_URI'];
    $_SERVER['REQUEST_URI'] = preg_replace('#^/en/staff#', '/staff', $_SERVER['REQUEST_URI']);

    if (!empty($matches[2])) {
        $_GET['staff_slug']        = $matches[2];
        $_GET['staff_context']     = 'en';
        $_REQUEST['staff_slug']    = $matches[2];
        $_REQUEST['staff_context'] = 'en';
    }

    add_filter('wpml_is_redirected', '__return_false', 1);
    add_filter('redirect_canonical', '__return_false', 1);

    add_action('parse_request', function($wp) use ($matches) {
        if (!empty($matches[2])) {
            $wp->query_vars['staff_slug']     = $matches[2];
            $wp->query_vars['staff_context']  = 'en';
            $wp->query_vars['staff_possible'] = '1';
        }
    }, 1);
}
MUPLUGIN
);

// ── Auto-updater ──────────────────────────────────────────────────────────────
// Checks a remote JSON manifest on alternativ.co.il and surfaces a standard
// WordPress "update available" notice when a newer version is published.
class Haifa_Staff_V2_Updater {

    private $plugin_slug;
    private $plugin_file;
    private $manifest_url;
    private $zip_url;
    private $current_version;

    public function __construct() {
        $this->plugin_slug     = 'haifa-staff-v2/haifa-staff-v2.php';
        $this->plugin_file     = __FILE__;
        $this->manifest_url    = 'https://alternativ.co.il/plugins/haifa-staff-v2.json';
        $this->zip_url         = 'https://alternativ.co.il/plugins/haifa-staff-v2.zip';
        $this->current_version = HAIFA_STAFF_V2_VERSION;

        add_filter('pre_set_site_transient_update_plugins', [$this, 'check_for_update']);
        add_filter('plugins_api',                           [$this, 'plugin_info'], 10, 3);
        add_filter('update_plugins_alternativ.co.il',      [$this, 'handle_update_check'], 10, 4);
        add_filter('language_attributes',                  [$this, 'maybe_set_ltr_attributes']);
    }

    // Fetch remote manifest (cached 12h).
    private function get_remote_data(): ?array {
        $cache = get_transient('haifa_staff_v2_update_data');
        if ($cache) return $cache;

        $response = wp_remote_get($this->manifest_url, ['timeout' => 10]);
        if (is_wp_error($response)) return null;

        $data = json_decode(wp_remote_retrieve_body($response), true);
        if (empty($data['version'])) return null;

        set_transient('haifa_staff_v2_update_data', $data, 12 * HOUR_IN_SECONDS);
        return $data;
    }

    // On /en/ URLs, switch <html> to dir="ltr" lang="en" so the theme
    // header/footer render correctly in LTR layout.
    public function maybe_set_ltr_attributes($output) {
        $uri = $_SERVER['REQUEST_URI'] ?? '';
        if (preg_match('#(^|/)en/#', $uri)) {
            $output = str_replace('dir="rtl"',    'dir="ltr"', $output);
            $output = str_replace('lang="he-IL"', 'lang="en"', $output);
        }
        return $output;
    }

    // Inject update info into WP transient so the plugins list shows the notice.
    public function check_for_update($transient) {
        if (empty($transient->checked)) return $transient;
        $remote = $this->get_remote_data();
        if (!$remote) return $transient;
        if (version_compare($this->current_version, $remote['version'], '<')) {
            $transient->response[$this->plugin_slug] = (object)[
                'slug'        => 'haifa-staff-v2',
                'plugin'      => $this->plugin_slug,
                'new_version' => $remote['version'],
                'url'         => $remote['details_url'] ?? 'https://alternativ.co.il/plugins/haifa-staff-v2',
                'package'     => $this->zip_url,
            ];
        }
        return $transient;
    }

    // Required for Update URI header — WordPress fires this for non-wp.org plugins.
    public function handle_update_check($update, $plugin_data, $plugin_file, $locales) {
        if ($plugin_file !== $this->plugin_slug) return $update;
        $remote = $this->get_remote_data();
        if (!$remote) return false;
        if (version_compare($this->current_version, $remote['version'], '<')) {
            return (object)[
                'slug'        => 'haifa-staff-v2',
                'plugin'      => $this->plugin_slug,
                'new_version' => $remote['version'],
                'url'         => $remote['details_url'] ?? 'https://alternativ.co.il/plugins/haifa-staff-v2',
                'package'     => $this->zip_url,
            ];
        }
        return false;
    }

    // Provide plugin details popup in wp-admin.
    public function plugin_info($result, $action, $args) {
        if ($action !== 'plugin_information') return $result;
        if (($args->slug ?? '') !== 'haifa-staff-v2') return $result;
        $remote = $this->get_remote_data();
        if (!$remote) return $result;
        return (object)[
            'name'          => 'אוניברסיטת חיפה - אנשי סגל',
            'slug'          => 'haifa-staff-v2',
            'version'       => $remote['version'],
            'author'        => '<a href="https://alternativ.co.il">Benny Mozes</a>',
            'homepage'      => 'https://alternativ.co.il/plugins/haifa-staff-v2',
            'requires'      => $remote['requires_wp']  ?? '6.0',
            'requires_php'  => $remote['requires_php'] ?? '8.0',
            'download_link' => $this->zip_url,
            'sections'      => [
                'description' => $remote['description'] ?? '',
                'changelog'   => $remote['changelog']   ?? '',
            ],
            'icons'   => [
                '1x' => 'https://alternativ.co.il/plugins/haifa-staff/icon-128x128.png',
                '2x' => 'https://alternativ.co.il/plugins/haifa-staff/icon-256x256.png',
            ],
            'banners' => [
                'low'  => 'https://alternativ.co.il/plugins/haifa-staff/banner-772x250.png',
                'high' => 'https://alternativ.co.il/plugins/haifa-staff/banner-772x250.png',
            ],
        ];
    }
}

new Haifa_Staff_V2_Updater();

require_once HAIFA_STAFF_V2_PLUGIN_DIR . 'includes/staff-filter-admin.php';
require_once HAIFA_STAFF_V2_PLUGIN_DIR . 'includes/staff-meta-box.php';
require_once HAIFA_STAFF_V2_PLUGIN_DIR . 'includes/elementor-staff-advanced-query.php';

// ── Elementor widget ──────────────────────────────────────────────────────────
function haifa_staff_v2_register_elementor_widgets() {
    if (!did_action('elementor/loaded')) return;
    require_once HAIFA_STAFF_V2_PLUGIN_DIR . 'includes/elementor-staff-grid-widget.php';
    \Elementor\Plugin::instance()->widgets_manager->register(new \Haifa_Staff_Grid_Widget());
}
add_action('elementor/widgets/register', 'haifa_staff_v2_register_elementor_widgets');

function haifa_staff_v2_add_elementor_categories($elements_manager) {
    $elements_manager->add_category('university', [
        'title' => __('אוניברסיטה', 'haifa-staff'),
        'icon'  => 'fa fa-university',
    ]);
}
add_action('elementor/elements/categories_registered', 'haifa_staff_v2_add_elementor_categories');

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Read a staff meta field. Mirrors ACF get_field() for simple scalar fields.
 * For staff_image returns the attachment ID (integer).
 * For staff_type / staff_academic_type returns the stored value
 * (WP auto-unserializes arrays on get).
 */
function haifa_v2_get_field(string $name, $post_id = null) {
    if (!$post_id) $post_id = get_the_ID();
    return get_post_meta($post_id, $name, true);
}

/**
 * Return all socials rows for a post as [ ['platform'=>..,'url'=>..], ... ]
 */
function haifa_v2_get_socials($post_id = null): array {
    if (!$post_id) $post_id = get_the_ID();
    $count = (int) get_post_meta($post_id, 'socials', true);
    $rows  = [];
    for ($i = 0; $i < $count; $i++) {
        $platform = get_post_meta($post_id, "socials_{$i}_platform", true);
        $url      = get_post_meta($post_id, "socials_{$i}_url",      true);
        if ($platform && $url) $rows[] = ['platform' => $platform, 'url' => $url];
    }
    return $rows;
}

/**
 * Resolve title_main key → Hebrew display label.
 * Single source of truth — all files must delegate to this function.
 * Handles v2 keys, legacy v1 keys, and custom title options stored in wp_options.
 */
function haifa_v2_title_label(string $value): string {
    $map = [
        // v2 keys
        'mr'    => 'מר',
        'mrs'   => "גב'",
        'dr'    => 'ד"ר',
        'prof'  => "פרופ'",
        'other' => 'אחר',
        // v1 fallback keys (legacy migration)
        'professor'           => 'מר',
        'associate_professor' => "גב'",
        'assistant_professor' => 'ד"ר',
        'lecturer'            => "פרופ'",
    ];
    if (isset($map[$value])) return $map[$value];
    $custom = json_decode(get_option('haifa_staff_custom_title_main', '[]'), true);
    if (is_array($custom)) {
        foreach ($custom as $opt) {
            if (($opt['value'] ?? '') === $value) return $opt['label'];
        }
    }
    return $value;
}

// ── Main plugin class ─────────────────────────────────────────────────────────
class HaifaStaffPluginV2 {

    protected $post_type = 'staff';

    public function __construct() {
        add_action('init', [$this, 'init']);
        add_action('init', [$this, 'register_cpt'], 0);
        add_action('init', [$this, 'add_staff_rewrite_rules']);
        add_action('template_redirect', [$this, 'maybe_load_staff_template'], 5);
        add_filter('query_vars',            [$this, 'add_staff_query_vars']);
        add_action('admin_enqueue_scripts', [$this, 'enqueue_admin_assets']);
        add_filter('use_block_editor_for_post_type', [$this, 'disable_gutenberg'], 10, 2);
        add_filter('document_title_parts',  [$this, 'maybe_translate_page_title']);

        add_action('save_post',     [$this, 'handle_cris_mutual_exclusion'], 20);

        add_shortcode('staff_social_links', [$this, 'shortcode_staff_social_links']);
        add_shortcode('acf_label',          [$this, 'display_acf_choice_label_shortcode']);
        add_filter('do_shortcode_tag',      [$this, 'filter_acf_label_output'], 10, 3);
        add_action('pre_get_posts',         [$this, 'order_staff_queries']);

        add_action('template_redirect', [$this, 'hide_administrative_staff'], 1);
        add_action('wp',        [$this, 'fix_staff_query_early'], 1);
        add_action('wp_head',   [$this, 'add_noindex_for_administrative_staff'], 1);
        add_action('wp_head',   [$this, 'add_structured_data_for_staff'], 10);
        add_filter('post_type_link', [$this, 'improve_staff_permalinks'], 10, 2);

        add_filter('single_template',  [$this, 'load_staff_single_template']);
        add_filter('archive_template', [$this, 'load_staff_archive_template']);

        add_filter('post_class', [$this, 'add_staff_type_class'], 10, 3);
        add_filter('elementor/frontend/the_content', [$this, 'add_staff_type_to_elementor_loop'], 10, 1);

        add_filter('post_row_actions', [$this, 'add_duplicate_link'], 10, 2);
        add_action('admin_action_duplicate_staff', [$this, 'duplicate_staff_post']);
        add_action('rest_api_init',  [$this, 'register_rest_api']);
        add_action('admin_menu',     [$this, 'register_bulk_edit_page']);
        add_action('admin_menu',     [$this, 'register_settings_page']);
        add_action('admin_init',     [$this, 'handle_bulk_edit_save']);

        // Hide the ACF field group from the edit screen (fields are rendered by our
        // own meta box) but keep the local field group registered so Elementor
        // dynamic tags can still resolve field values via ACF.
        add_action('acf/input/admin_head', function() {
            global $post;
            if ($post && $post->post_type === 'staff') {
                echo '<style>#acf-group_staffs_details { display: none !important; }</style>';
                // Suppress ACF required-field validation for the staff CPT
                // (our own meta box handles validation).
                echo '<script>document.addEventListener("DOMContentLoaded",function(){';
                echo 'if(typeof acf!=="undefined"){acf.addFilter("validation_complete",function(json,$form){json.valid=1;json.errors=[];return json;});}';
                echo '});</script>';
            }
        });
        add_filter('acf/validate_save_post', function() {
            global $post;
            if ($post && $post->post_type === 'staff') acf_reset_validation_errors();
        }, 99);

        register_activation_hook(__FILE__,   [$this, 'activate']);
        register_deactivation_hook(__FILE__, [$this, 'deactivate']);
    }

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    public function init() {
        load_plugin_textdomain('haifa-staff', false, dirname(plugin_basename(__FILE__)) . '/languages');
    }

    public function activate() {
        $this->register_cpt();
        $this->add_staff_rewrite_rules();
        flush_rewrite_rules();
    }

    public function deactivate() {
        flush_rewrite_rules();
    }

    // ── CPT ───────────────────────────────────────────────────────────────────

    public function register_cpt() {
        if (post_type_exists($this->post_type)) return;

        $cpt_json = HAIFA_STAFF_V2_PLUGIN_DIR . 'assets/acf-cpt.json';
        if (!file_exists($cpt_json)) return;

        $settings = json_decode(file_get_contents($cpt_json), true);
        if (is_array($settings) && isset($settings['post_type']) && $settings['post_type'] === $this->post_type) {
            if (isset($settings['labels'], $settings['supports'])) {
                register_post_type($this->post_type, $settings);
            }
        }

        // Register ACF field group locally so Elementor dynamic tags work
        // even without ACF field groups saved in the database.
        // Location rules are stripped so the group never renders on edit screens.
        if (function_exists('acf_add_local_field_group')) {
            $fields_json = HAIFA_STAFF_V2_PLUGIN_DIR . 'assets/acf-staff-fields.json';
            if (file_exists($fields_json)) {
                $field_group = json_decode(file_get_contents($fields_json), true);
                if ($field_group) {
                    $group = isset($field_group[0]) ? $field_group[0] : $field_group;
                    $group['location'] = [];
                    acf_add_local_field_group($group);
                }
            }
        }
    }

    // ── Assets ────────────────────────────────────────────────────────────────

    public function enqueue_admin_assets($hook) {
        $screen = get_current_screen();
        if (!$screen || $screen->post_type !== $this->post_type) return;
        if (!in_array($hook, ['post.php', 'post-new.php', 'edit.php'], true)) return;

        $css = HAIFA_STAFF_V2_PLUGIN_DIR . 'assets/admin.css';
        if (file_exists($css)) {
            wp_enqueue_style('haifa-staff-v2-admin', HAIFA_STAFF_V2_PLUGIN_URL . 'assets/admin.css', [], filemtime($css));
        }
    }

    public function disable_gutenberg($enabled, $post_type) {
        return ($post_type === $this->post_type) ? false : $enabled;
    }

    // ── Page title translation ────────────────────────────────────────────────
    // Reads page_title / page_title_en from the Elementor staff grid widget
    // settings and injects the correct language version into the <title> tag.

    public function maybe_translate_page_title($title) {
        $page_id = get_queried_object_id();
        if (!$page_id) return $title;

        $elementor_data = get_post_meta($page_id, '_elementor_data', true);
        if (empty($elementor_data)) return $title;

        $data = json_decode($elementor_data, true);
        if (!is_array($data)) return $title;

        $uri      = $_SERVER['REQUEST_URI'] ?? '';
        $is_en    = (bool) preg_match('#(^|/)en/#', $uri);
        $key      = $is_en ? 'page_title_en' : 'page_title';
        $new_title = $this->find_elementor_widget_setting($data, 'haifa_staff_grid', $key);
        if (!empty($new_title)) $title['title'] = $new_title;

        return $title;
    }

    // Recursively search Elementor elements tree for a specific widget setting.
    private function find_elementor_widget_setting($elements, $widget_name, $setting_key) {
        foreach ($elements as $element) {
            if (isset($element['widgetType']) && $element['widgetType'] === $widget_name) {
                return $element['settings'][$setting_key] ?? '';
            }
            if (!empty($element['elements'])) {
                $found = $this->find_elementor_widget_setting($element['elements'], $widget_name, $setting_key);
                if ($found) return $found;
            }
        }
        return '';
    }

    // ── Admin menu: Bulk edit ─────────────────────────────────────────────────

    public function register_bulk_edit_page() {
        add_submenu_page(
            'edit.php?post_type=staff',
            'עדכון רשימת סגל',
            'עדכון רשימת סגל',
            'edit_posts',
            'haifa-staff-bulk-edit',
            function() { require_once HAIFA_STAFF_V2_PLUGIN_DIR . 'includes/staff-bulk-edit.php'; }
        );
    }

    // ── Admin menu: Settings ──────────────────────────────────────────────────

    public function register_settings_page() {
        add_submenu_page(
            'edit.php?post_type=staff',
            'הגדרות תוסף סגל',
            'הגדרות',
            'manage_options',
            'haifa-staff-settings',
            [$this, 'render_settings_page']
        );
    }

    // Renders the settings page. Handles the Install/Remove mu-plugin actions
    // and displays WPML detection + current mu-plugin status.
    public function render_settings_page() {
        if (!current_user_can('manage_options')) return;

        $mu_file      = WPMU_PLUGIN_DIR . '/haifa-staff-wpml-fix.php';
        $is_installed = file_exists($mu_file);
        $wpml_active  = defined('ICL_SITEPRESS_VERSION') || class_exists('SitePress');
        $message      = '';
        $message_type = 'success';

        if (isset($_POST['haifa_staff_settings_action'])) {
            check_admin_referer('haifa_staff_settings_nonce');

            $action = sanitize_text_field($_POST['haifa_staff_settings_action']);

            if ($action === 'install') {
                if (!is_dir(WPMU_PLUGIN_DIR)) wp_mkdir_p(WPMU_PLUGIN_DIR);
                $result = file_put_contents($mu_file, HAIFA_STAFF_WPML_FIX_CONTENT);
                if ($result !== false) {
                    $is_installed = true;
                    $message      = 'ה-MU Plugin הותקן בהצלחה ב: ' . esc_html($mu_file);
                } else {
                    $message_type = 'error';
                    $message      = 'שגיאה: לא ניתן לכתוב לתיקייה ' . esc_html(WPMU_PLUGIN_DIR) . '. בדוק הרשאות כתיבה.';
                }

            } elseif ($action === 'remove') {
                if ($is_installed && unlink($mu_file)) {
                    $is_installed = false;
                    $message      = 'ה-MU Plugin הוסר בהצלחה.';
                } else {
                    $message_type = 'error';
                    $message      = 'שגיאה: לא ניתן למחוק את הקובץ ' . esc_html($mu_file);
                }
            }
        }
        ?>
        <div class="wrap" dir="rtl">
            <h1>הגדרות תוסף אנשי סגל</h1>

            <?php if ($message): ?>
                <div class="notice notice-<?php echo $message_type; ?> is-dismissible"><p><?php echo $message; ?></p></div>
            <?php endif; ?>

            <table class="widefat" style="max-width:600px;margin-top:20px;">
                <tbody>
                    <tr>
                        <th style="width:200px;">גרסת תוסף</th>
                        <td><?php echo esc_html(HAIFA_STAFF_V2_VERSION); ?></td>
                    </tr>
                    <tr>
                        <th>WPML</th>
                        <td>
                            <?php if ($wpml_active): ?>
                                <span style="color:#2a9d2a;">&#10003; פעיל באתר זה</span>
                            <?php else: ?>
                                <span style="color:#888;">&#10007; לא מזוהה</span>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th>MU Plugin (תיקון WPML)</th>
                        <td>
                            <?php if ($is_installed): ?>
                                <span style="color:#2a9d2a;">&#10003; מותקן</span>
                                <br><small style="color:#888;"><?php echo esc_html($mu_file); ?></small>
                            <?php else: ?>
                                <span style="color:#c0392b;">&#10007; לא מותקן</span>
                            <?php endif; ?>
                        </td>
                    </tr>
                </tbody>
            </table>

            <?php if ($wpml_active && !$is_installed): ?>
                <div class="notice notice-warning" style="max-width:600px;margin-top:12px;">
                    <p><strong>WPML מזוהה אך ה-MU Plugin אינו מותקן.</strong> ללא התקנתו, כתובות <code>/en/staff/</code> ייחסמו על ידי WPML.</p>
                </div>
            <?php elseif (!$wpml_active && $is_installed): ?>
                <div class="notice notice-info" style="max-width:600px;margin-top:12px;">
                    <p>ה-MU Plugin מותקן אך WPML אינו פעיל באתר זה. ניתן להסירו אם אינו נדרש.</p>
                </div>
            <?php elseif ($wpml_active && $is_installed): ?>
                <div class="notice notice-success" style="max-width:600px;margin-top:12px;">
                    <p>ההגדרה תקינה — WPML פעיל וה-MU Plugin מותקן.</p>
                </div>
            <?php endif; ?>

            <form method="post" style="margin-top:20px;">
                <?php wp_nonce_field('haifa_staff_settings_nonce'); ?>
                <?php if (!$is_installed): ?>
                    <button type="submit" name="haifa_staff_settings_action" value="install" class="button button-primary">התקן MU Plugin</button>
                <?php else: ?>
                    <button type="submit" name="haifa_staff_settings_action" value="remove" class="button button-secondary"
                        onclick="return confirm('האם אתה בטוח שברצונך להסיר את ה-MU Plugin?');">הסר MU Plugin</button>
                <?php endif; ?>
            </form>

            <hr style="max-width:600px;margin-top:30px;">
            <h3>מה עושה ה-MU Plugin?</h3>
            <p style="max-width:600px;color:#555;">
                כאשר WPML פעיל באתר, הוא מיירט כתובות <code>/en/staff/</code> ומנסה להפנות אותן לפי הגדרות השפה שלו —
                מה שגורם לשגיאות 404 או תצוגה שגויה של פרופילי הסגל באנגלית.<br><br>
                ה-MU Plugin רץ לפני כל תוסף אחר ומונע את ההפניה הזו, כך שתוסף הסגל יכול לטפל בכתובות האלה בעצמו.
            </p>
        </div>
        <?php
    }

    // ── Bulk edit save ────────────────────────────────────────────────────────

    public function handle_bulk_edit_save() {
        if (!isset($_POST['hsbe_nonce'])) return;
        check_admin_referer('hsbe_save', 'hsbe_nonce');
        if (!current_user_can('edit_posts')) return;

        $url_keys     = ['cris_website', 'personal_website'];
        $email_keys   = ['email'];
        $multi_keys   = ['staff_type'];
        $allowed_keys = [
            'title_main','first_name','last_name','status','position',
            'staff_type','staff_academic_type','academic_degree_main',
            'email','external_phone','inner_phone','cris_website','personal_website',
        ];

        $data = $_POST['staff'] ?? [];
        foreach ($data as $post_id => $values) {
            $post_id = (int) $post_id;
            if (!$post_id || get_post_type($post_id) !== 'staff') continue;
            foreach ($values as $key => $val) {
                if (!in_array($key, $allowed_keys, true)) continue;
                if (in_array($key, $multi_keys, true)) {
                    update_post_meta($post_id, $key, array_map('sanitize_text_field', (array)$val));
                } elseif (in_array($key, $url_keys, true)) {
                    update_post_meta($post_id, $key, esc_url_raw($val));
                } elseif (in_array($key, $email_keys, true)) {
                    update_post_meta($post_id, $key, sanitize_email($val));
                } else {
                    update_post_meta($post_id, $key, sanitize_text_field($val));
                }
            }
        }

        wp_redirect(admin_url('edit.php?post_type=staff&page=haifa-staff-bulk-edit&hsbe_saved=1'));
        exit;
    }

    // ── Rewrite rules ─────────────────────────────────────────────────────────

    public function add_staff_rewrite_rules() {
        // Virtual /en/ prefix — passes through to the same WordPress page;
        // REQUEST_URI retains /en/ so templates can detect language.
        add_rewrite_rule('^en/(.+?)/?$', 'index.php?pagename=$matches[1]', 'top');

        // Staff profile URLs: /page-context/staff-slug/
        add_rewrite_rule(
            '^(.+)/([^/]+)/?$',
            'index.php?staff_possible=1&staff_context=$matches[1]&staff_slug=$matches[2]',
            'bottom'
        );
    }

    public function add_staff_query_vars($vars) {
        $vars[] = 'staff_context';
        $vars[] = 'staff_slug';
        $vars[] = 'staff_possible';
        return $vars;
    }

    // ── Template loading ──────────────────────────────────────────────────────

    // Intercepts template_redirect and serves single-staff.php when a staff
    // member's slug is found in the URL. Handles both query-var and URL-parsed paths,
    // plus WPML fallback via HAIFA_STAFF_ORIGINAL_URI.
    public function maybe_load_staff_template() {
        $staff_slug    = get_query_var('staff_slug');
        $staff_context = get_query_var('staff_context');

        // Fallback: parse URL directly when page rules fire before our rewrite
        if (empty($staff_slug)) {
            $path  = trim(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH), '/');
            $parts = explode('/', $path);
            if (count($parts) >= 2) {
                $staff_slug    = array_pop($parts);
                $staff_context = implode('/', $parts);
            }
        }

        // WPML fallback: restore language context from the original URI
        // (WPML rewrites REQUEST_URI before our rewrite fires)
        if (!empty($_SERVER['HAIFA_STAFF_ORIGINAL_URI'])) {
            $orig = trim(parse_url($_SERVER['HAIFA_STAFF_ORIGINAL_URI'], PHP_URL_PATH), '/');
            if (preg_match('#^en/#', $orig)) $staff_context = 'en';
        }

        if (empty($staff_slug)) return;

        $q = new WP_Query(['post_type' => 'staff', 'name' => $staff_slug, 'posts_per_page' => 1]);
        if ($q->have_posts()) {
            global $wp_query;
            $wp_query              = $q;
            $wp_query->is_404      = false;
            $wp_query->is_singular = true;
            $wp_query->is_single   = true;
            set_query_var('staff_context', $staff_context);
            include HAIFA_STAFF_V2_PLUGIN_DIR . 'templates/single-staff.php';
            exit;
        }
    }

    // Runs on 'wp' hook (before title is computed) to set the correct queried
    // object so the <title> tag shows the staff member's name instead of 404.
    public function fix_staff_query_early() {
        $staff_slug = get_query_var('staff_slug');

        if (empty($staff_slug)) {
            $path  = trim(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH), '/');
            $parts = explode('/', $path);
            if (count($parts) >= 2) $staff_slug = array_pop($parts);
        }

        if (empty($staff_slug)) return;

        $q = new WP_Query(['post_type' => 'staff', 'name' => $staff_slug, 'posts_per_page' => 1]);
        if (!$q->have_posts()) return;

        global $wp_query;
        $wp_query                    = $q;
        $wp_query->is_404            = false;
        $wp_query->is_singular       = true;
        $wp_query->is_single         = true;
        $wp_query->queried_object    = $q->post;
        $wp_query->queried_object_id = $q->post->ID;
    }

    // ── CRIS mutual exclusion ─────────────────────────────────────────────────
    // Senior staff use cris_website; junior staff use cris_website_2.
    // Clear the other field on save to keep data clean.

    public function handle_cris_mutual_exclusion($post_id) {
        if (get_post_type($post_id) !== $this->post_type) return;
        if (defined('DOING_AUTOSAVE') && DOING_AUTOSAVE) return;
        if (!isset($_POST['haifa_staff_v2_nonce'])) return;

        $type = sanitize_text_field($_POST['staff_academic_type'] ?? '');
        if ($type === 'senior') {
            update_post_meta($post_id, 'cris_website_2', '');
        } elseif ($type === 'junior') {
            update_post_meta($post_id, 'cris_website', '');
        }
    }

    // ── Shortcodes ────────────────────────────────────────────────────────────

    public function shortcode_staff_social_links($atts) {
        $post_id = get_the_ID();
        $socials = haifa_v2_get_socials($post_id);
        if (empty($socials)) return '';

        $icons = [
            'facebook'     => 'fab fa-facebook-f',
            'twitter'      => 'fab fa-x-twitter',
            'linkedin'     => 'fab fa-linkedin-in',
            'instagram'    => 'fab fa-instagram',
            'youtube'      => 'fab fa-youtube',
            'tiktok'       => 'fab fa-tiktok',
            'researchgate' => 'fab fa-researchgate',
            'website'      => 'fas fa-globe',
            'other'        => 'fas fa-link',
        ];

        $out = '<ul class="staff-social-links">';
        foreach ($socials as $row) {
            $icon = $icons[$row['platform']] ?? 'fas fa-link';
            $out .= '<li><a href="' . esc_url($row['url']) . '" target="_blank" rel="noopener noreferrer">';
            $out .= '<i class="' . esc_attr($icon) . '"></i></a></li>';
        }
        return $out . '</ul>';
    }

    // [acf_label name="field_name"] — resolves a field key to its display label.
    public function display_acf_choice_label_shortcode($atts) {
        $atts = shortcode_atts(['name' => ''], $atts, 'acf_label');
        if (empty($atts['name'])) return '';

        $choices_map = [
            'status'              => ['alive' => 'פעיל', 'retired' => 'גימלאות', 'dead' => 'נפטר'],
            'title_main'          => ['mr' => 'מר', 'mrs' => "גב'", 'dr' => 'ד"ר', 'prof' => "פרופ'", 'other' => 'אחר'],
            'staff_academic_type' => ['senior' => 'בכיר', 'junior' => 'זוטר'],
        ];

        $name  = $atts['name'];
        $value = haifa_v2_get_field($name);
        if (!$value) return '';

        return $choices_map[$name][$value] ?? $value;
    }

    // Hide "פעיל" / "גימלאות" status labels on frontend; show ז״ל for deceased.
    public function filter_acf_label_output($output, $tag, $attr) {
        if ($tag !== 'acf_label') return $output;
        if (empty($attr['name']) || ($attr['name'] !== 'field_staff_status' && $attr['name'] !== 'status')) return $output;
        if ($output === 'פעיל' || $output === 'גימלאות') return '';
        if ($output === 'נפטר') return 'ז״ל';
        return $output;
    }

    // ── Ordering ──────────────────────────────────────────────────────────────

    // Default frontend ordering: alphabetical by last_name.
    public function order_staff_queries($query) {
        if (is_admin()) return;

        $post_type = $query->get('post_type');
        if (empty($post_type)) {
            if (is_post_type_archive('staff') || is_tax('staff_category') || is_tax('staff_tag')) {
                $post_type = 'staff';
            }
        }
        if ($post_type !== 'staff' && !(is_array($post_type) && in_array('staff', $post_type, true))) return;
        if (!empty($query->get('post__in'))) return;

        $query->set('meta_key', 'last_name');
        $query->set('orderby',  'meta_value');
        $query->set('order',    'ASC');
    }

    // ── SEO / Admin hiding ────────────────────────────────────────────────────

    // Returns true if the post is administrative-only (not academic).
    private function is_admin_only_staff($post_id): bool {
        $types = get_post_meta($post_id, 'staff_type', true);
        if (!is_array($types)) return false;
        return in_array('administrative', $types, true) && !in_array('academic', $types, true);
    }

    // Redirect administrative-only staff profiles to home (they should not be publicly accessible).
    public function hide_administrative_staff() {
        if (!is_singular('staff')) return;
        if ($this->is_admin_only_staff(get_the_ID())) {
            status_header(404);
            nocache_headers();
            wp_redirect(home_url('/'), 301);
            exit;
        }
    }

    public function add_noindex_for_administrative_staff() {
        if (!is_singular('staff')) return;
        if ($this->is_admin_only_staff(get_the_ID())) {
            echo '<meta name="robots" content="noindex, nofollow" />' . "\n";
        }
    }

    // Outputs schema.org Person structured data for academic staff profiles.
    public function add_structured_data_for_staff() {
        if (!is_singular('staff')) return;
        $post_id = get_the_ID();
        if ($this->is_admin_only_staff($post_id)) return;

        $first_name = get_post_meta($post_id, 'first_name', true);
        $last_name  = get_post_meta($post_id, 'last_name',  true);
        $email      = get_post_meta($post_id, 'email',      true);
        $phone      = get_post_meta($post_id, 'external_phone', true);
        $about      = get_post_meta($post_id, 'about',      true);
        $img_id     = get_post_meta($post_id, 'staff_image', true);
        $staff_type = get_post_meta($post_id, 'staff_type',  true);

        $schema = [
            '@context' => 'https://schema.org',
            '@type'    => 'Person',
            'name'     => trim($first_name . ' ' . $last_name),
            'url'      => get_permalink($post_id),
        ];
        if ($first_name) $schema['givenName']   = $first_name;
        if ($last_name)  $schema['familyName']  = $last_name;
        if ($email)      $schema['email']       = $email;
        if ($phone)      $schema['telephone']   = $phone;
        if ($about)      $schema['description'] = wp_strip_all_tags(substr($about, 0, 300));
        if ($img_id)     $schema['image']       = wp_get_attachment_image_url((int)$img_id, 'full') ?: '';

        if (is_array($staff_type) && in_array('academic', $staff_type, true)) {
            $schema['affiliation'] = ['@type' => 'Organization', 'name' => 'University of Haifa', 'url' => 'https://www.haifa.ac.il'];
            $schema['jobTitle']    = 'Academic Staff';
        }

        echo '<script type="application/ld+json">' . "\n";
        echo wp_json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        echo "\n" . '</script>' . "\n";
    }

    // ── CSS Classes ───────────────────────────────────────────────────────────

    // Adds staff-type-* classes to post_class for theme/template targeting.
    public function add_staff_type_class($classes, $class, $post_id) {
        if (get_post_type($post_id) !== 'staff') return $classes;
        $types = get_post_meta($post_id, 'staff_type', true);
        if (is_array($types)) {
            foreach ($types as $t) $classes[] = 'staff-type-' . sanitize_html_class($t);
        }
        return $classes;
    }

    // Injects staff-type-* classes into Elementor Loop Grid item wrappers.
    public function add_staff_type_to_elementor_loop($content) {
        if (get_post_type() !== 'staff') return $content;
        $types = get_post_meta(get_the_ID(), 'staff_type', true);
        if (!is_array($types)) return $content;
        $extra = '';
        foreach ($types as $t) $extra .= ' staff-type-' . sanitize_html_class($t);
        return preg_replace('/class="([^"]*\be-loop-item\b[^"]*)"/', 'class="$1' . $extra . '"', $content, 1);
    }

    // ── Templates ─────────────────────────────────────────────────────────────

    public function load_staff_single_template($template) {
        if (!is_singular('staff')) return $template;
        $theme  = locate_template(['single-staff.php']);
        if ($theme) return $theme;
        $plugin = HAIFA_STAFF_V2_PLUGIN_DIR . 'templates/single-staff.php';
        return file_exists($plugin) ? $plugin : $template;
    }

    public function load_staff_archive_template($template) {
        if (!is_post_type_archive('staff')) return $template;
        $theme  = locate_template(['archive-staff.php']);
        if ($theme) return $theme;
        $plugin = HAIFA_STAFF_V2_PLUGIN_DIR . 'templates/archive-staff.php';
        return file_exists($plugin) ? $plugin : $template;
    }

    // Builds a hierarchical permalink based on the current page's ancestor path.
    // Used so staff profile URLs mirror the page tree: /faculty/staff/person/
    public function improve_staff_permalinks($link, $post) {
        if (is_admin()) return $link;
        if (!$post || $post->post_type !== 'staff') return $link;
        if (!is_page()) return $link;

        $current_page_id = get_queried_object_id();
        if (!$current_page_id) return $link;

        $ancestors   = array_reverse(get_post_ancestors($current_page_id));
        $ancestors[] = $current_page_id;

        $path_parts = [];
        foreach ($ancestors as $ancestor_id) {
            $ancestor = get_post($ancestor_id);
            if ($ancestor) $path_parts[] = $ancestor->post_name;
        }

        if (empty($path_parts)) return $link;
        return home_url('/' . implode('/', $path_parts) . '/' . $post->post_name . '/');
    }

    // ── Duplicate post ────────────────────────────────────────────────────────

    public function add_duplicate_link($actions, $post) {
        if ($post->post_type === 'staff' && current_user_can('edit_posts')) {
            $url = wp_nonce_url(admin_url('admin.php?action=duplicate_staff&post=' . $post->ID), 'duplicate_staff_' . $post->ID);
            $actions['duplicate'] = '<a href="' . esc_url($url) . '">' . __('שכפל', 'haifa-staff') . '</a>';
        }
        return $actions;
    }

    public function duplicate_staff_post() {
        if (!isset($_GET['post'])) wp_die('לא נבחר פוסט');
        $post_id = absint($_GET['post']);
        check_admin_referer('duplicate_staff_' . $post_id);
        if (!current_user_can('edit_posts')) wp_die('אין הרשאה');
        $post = get_post($post_id);
        if (!$post || $post->post_type !== 'staff') wp_die('פוסט לא תקין');

        $new_id = wp_insert_post([
            'post_title'   => $post->post_title . ' (עותק)',
            'post_content' => $post->post_content,
            'post_status'  => 'draft',
            'post_type'    => 'staff',
            'post_author'  => get_current_user_id(),
        ]);
        if (is_wp_error($new_id)) wp_die('שגיאה בשכפול');

        // Copy all post meta, skipping internal WP keys.
        $all_meta = get_post_meta($post_id);
        foreach ($all_meta as $key => $values) {
            if (str_starts_with($key, '_')) continue;
            foreach ($values as $val) {
                add_post_meta($new_id, $key, maybe_unserialize($val));
            }
        }

        wp_redirect(admin_url('post.php?action=edit&post=' . $new_id));
        exit;
    }

    // ── REST API ──────────────────────────────────────────────────────────────
    // Provides cross-site aggregation endpoints used by the central university
    // portal to pull staff data from each faculty site.

    public function register_rest_api() {
        $ns = 'haifa-staff/v1';

        register_rest_route($ns, '/staff', [
            'methods'             => 'GET',
            'callback'            => [$this, 'rest_get_staff_list'],
            'permission_callback' => '__return_true',
            'args'                => [
                'staff_type'          => ['type' => 'string', 'sanitize_callback' => 'sanitize_text_field'],
                'staff_academic_type' => ['type' => 'string', 'sanitize_callback' => 'sanitize_text_field'],
                'status'              => ['type' => 'string', 'sanitize_callback' => 'sanitize_text_field'],
                'tag'                 => ['type' => 'string', 'sanitize_callback' => 'sanitize_text_field'],
            ],
        ]);

        register_rest_route($ns, '/staff/(?P<slug>[^/]+)', [
            'methods'             => 'GET',
            'callback'            => [$this, 'rest_get_staff_single'],
            'permission_callback' => '__return_true',
            'args'                => [
                'slug' => ['type' => 'string', 'sanitize_callback' => 'sanitize_text_field'],
            ],
        ]);

        register_rest_route($ns, '/tags', [
            'methods'             => 'GET',
            'callback'            => [$this, 'rest_get_tags'],
            'permission_callback' => '__return_true',
        ]);
    }

    public function rest_get_staff_list(WP_REST_Request $request): WP_REST_Response {
        $meta_query = [['key' => 'staff_type', 'value' => 'administrative', 'compare' => 'NOT LIKE']];

        if ($request->get_param('staff_type')) {
            $meta_query[] = ['key' => 'staff_type', 'value' => $request->get_param('staff_type'), 'compare' => 'LIKE'];
        }
        if ($request->get_param('staff_academic_type')) {
            $meta_query[] = ['key' => 'staff_academic_type', 'value' => $request->get_param('staff_academic_type'), 'compare' => '='];
        }
        if ($request->get_param('status')) {
            $meta_query[] = ['key' => 'status', 'value' => $request->get_param('status'), 'compare' => '='];
        }

        $args = [
            'post_type'      => 'staff',
            'post_status'    => 'publish',
            'posts_per_page' => -1,
            'meta_query'     => $meta_query,
        ];

        if ($request->get_param('tag')) $args['tag'] = $request->get_param('tag');

        $posts = get_posts($args);
        $data  = array_map([$this, 'haifa_v2_staff_post_to_api_item'], $posts);
        return new WP_REST_Response(array_values(array_filter($data)), 200);
    }

    public function rest_get_staff_single(WP_REST_Request $request): WP_REST_Response {
        $post = get_page_by_path($request->get_param('slug'), OBJECT, 'staff');
        if (!$post || $post->post_status !== 'publish') {
            return new WP_REST_Response(['error' => 'Not found'], 404);
        }
        $staff_type = get_post_meta($post->ID, 'staff_type', true);
        if (is_array($staff_type) && $staff_type === ['administrative']) {
            return new WP_REST_Response(['error' => 'Not found'], 404);
        }
        return new WP_REST_Response($this->haifa_v2_staff_post_to_api_item($post), 200);
    }

    public function rest_get_tags(WP_REST_Request $request): WP_REST_Response {
        $staff_ids = get_posts([
            'post_type'      => 'staff',
            'post_status'    => 'publish',
            'posts_per_page' => -1,
            'fields'         => 'ids',
        ]);

        if (empty($staff_ids)) return new WP_REST_Response([], 200);

        $terms = get_terms([
            'taxonomy'   => 'post_tag',
            'object_ids' => $staff_ids,
            'hide_empty' => true,
        ]);

        if (is_wp_error($terms)) return new WP_REST_Response([], 200);

        $data = array_map(function($t) {
            return ['slug' => $t->slug, 'name' => $t->name, 'count' => $t->count];
        }, $terms);
        return new WP_REST_Response($data, 200);
    }

    // Converts a staff WP_Post into the normalized array structure returned by the REST API.
    private function haifa_v2_staff_post_to_api_item(WP_Post $post): array {
        $id         = $post->ID;
        $staff_type = get_post_meta($id, 'staff_type', true);
        if (is_array($staff_type) && $staff_type === ['administrative']) return [];

        $title_main = get_post_meta($id, 'title_main', true);
        $photo_id   = get_post_meta($id, 'staff_image', true);
        $photo_url  = $photo_id ? wp_get_attachment_image_url((int)$photo_id, 'medium') : '';

        $tags = get_the_terms($id, 'post_tag');
        $tags = (!$tags || is_wp_error($tags)) ? [] : array_map(function($t) {
            return ['slug' => $t->slug, 'name' => $t->name];
        }, $tags);

        return [
            'id'                  => $id,
            'slug'                => $post->post_name,
            'profile_url'         => get_permalink($id),
            'first_name'          => get_post_meta($id, 'first_name',          true),
            'last_name'           => get_post_meta($id, 'last_name',           true),
            'title_main'          => $title_main,
            'title_main_label'    => haifa_v2_title_label((string)$title_main),
            'position'            => get_post_meta($id, 'position',            true),
            'status'              => get_post_meta($id, 'status',              true),
            'staff_type'          => is_array($staff_type) ? $staff_type : [],
            'staff_academic_type' => get_post_meta($id, 'staff_academic_type', true),
            'email'               => get_post_meta($id, 'email',               true),
            'cris_website'        => get_post_meta($id, 'cris_website',        true),
            'personal_website'    => get_post_meta($id, 'personal_website',    true),
            'photo_url'           => $photo_url ?: '',
            'about'               => get_post_meta($id, 'about',               true),
            'publications'        => get_post_meta($id, 'publications',        true),
            'education'           => get_post_meta($id, 'education',           true),
            'academic_background' => get_post_meta($id, 'academic_background', true),
            'reserach_areas'      => get_post_meta($id, 'reserach_areas',      true),
            'media'               => get_post_meta($id, 'media',               true),
            'prizes'              => get_post_meta($id, 'prizes',              true),
            'additional_info'     => get_post_meta($id, 'additional_info',     true),
            'socials'             => haifa_v2_get_socials($id),
            'tags'                => $tags,
        ];
    }
}

new HaifaStaffPluginV2();

// ── Staff page <title> fix ────────────────────────────────────────────────────
// WP, Yoast, and Rank Math all need the staff member's name in the title tag.
// We hook all three with priority 99 to override whatever they set.

function haifa_v2_get_staff_title_from_url(): string {
    $path  = trim(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH), '/');
    $parts = explode('/', $path);
    $slug  = end($parts);
    if (empty($slug)) return '';

    $post  = get_page_by_path($slug, OBJECT, 'staff');
    if (!$post) return '';

    $first = get_post_meta($post->ID, 'first_name', true);
    $last  = get_post_meta($post->ID, 'last_name',  true);
    return trim($first . ' ' . $last);
}

add_filter('pre_get_document_title', function($title) {
    $name = haifa_v2_get_staff_title_from_url();
    return $name ? $name . ' - ' . get_bloginfo('name') : $title;
}, 99);

add_filter('wpseo_title', function($title) {
    $name = haifa_v2_get_staff_title_from_url();
    return $name ? $name . ' - ' . get_bloginfo('name') : $title;
}, 99);

add_filter('rank_math/frontend/title', function($title) {
    $name = haifa_v2_get_staff_title_from_url();
    return $name ? $name . ' - ' . get_bloginfo('name') : $title;
}, 99);

// ── Canonical URL ─────────────────────────────────────────────────────────────
// Forces a single canonical for staff profiles and suppresses duplicate
// canonical tags from Yoast / Rank Math / AIOSEO.

add_action('template_redirect', function() {
    $path  = trim(parse_url($_SERVER['REQUEST_URI'] ?? '', PHP_URL_PATH), '/');
    $parts = explode('/', $path);
    if (count($parts) < 2) return;
    $slug = end($parts);
    $post = get_page_by_path($slug, OBJECT, 'staff');
    if (!$post) return;

    $canonical = get_permalink($post->ID);

    remove_action('wp_head', 'rel_canonical');
    add_filter('wpseo_canonical',              function() use ($canonical) { return $canonical; });
    add_filter('rank_math/frontend/canonical', function() use ($canonical) { return $canonical; });
    add_filter('aioseo_canonical_url',         function() use ($canonical) { return $canonical; });

    add_action('wp_head', function() use ($canonical) {
        echo '<link rel="canonical" href="' . esc_url($canonical) . '" />' . "\n";
    }, 1);
});

// Prevent WordPress from redirecting contextual staff URLs (/faculty/staff/person/).
add_filter('redirect_canonical', function($redirect_url, $requested_url) {
    $path  = trim(parse_url($requested_url, PHP_URL_PATH), '/');
    $parts = explode('/', $path);
    if (count($parts) >= 2) {
        $slug = end($parts);
        $post = get_page_by_path($slug, OBJECT, 'staff');
        if ($post) return false;
    }
    return $redirect_url;
}, 10, 2);

// ── Staff @mention (TinyMCE) ──────────────────────────────────────────────────
// Registers a TinyMCE plugin that shows a staff autocomplete dropdown when
// the editor user types @. Covers the classic editor, Elementor text widgets,
// and dynamically created TinyMCE instances via polling.

add_filter('mce_external_plugins', function($plugins) {
    $plugins['haifa_staff_mention'] = HAIFA_STAFF_V2_PLUGIN_URL . 'assets/staff-mention.js';
    return $plugins;
});

add_action('admin_head', function() {
    ?>
    <script>
    var haifaStaffMention = {
        ajaxUrl: <?php echo json_encode(admin_url('admin-ajax.php')); ?>,
        nonce:   <?php echo json_encode(wp_create_nonce('haifa_staff_mention')); ?>
    };
    </script>
    <?php
});

// AJAX: returns up to 10 staff matching the typed search term.
add_action('wp_ajax_haifa_staff_mention_search', function() {
    check_ajax_referer('haifa_staff_mention', 'nonce');
    $term      = sanitize_text_field($_GET['term'] ?? '');
    $title_map = ['mr' => 'מר', 'mrs' => "גב'", 'dr' => 'ד"ר', 'prof' => "פרופ'"];
    $posts     = get_posts([
        'post_type'      => 'staff',
        'posts_per_page' => 10,
        'post_status'    => 'publish',
        'meta_key'       => 'last_name',
        'orderby'        => 'meta_value',
        'order'          => 'ASC',
        'meta_query'     => [
            'relation' => 'OR',
            ['key' => 'first_name', 'value' => $term, 'compare' => 'LIKE'],
            ['key' => 'last_name',  'value' => $term, 'compare' => 'LIKE'],
        ],
    ]);
    $results = [];
    foreach ($posts as $p) {
        $fn      = get_post_meta($p->ID, 'first_name',  true);
        $ln      = get_post_meta($p->ID, 'last_name',   true);
        $tm      = get_post_meta($p->ID, 'title_main',  true);
        $to      = get_post_meta($p->ID, 'title_other', true);
        $tl      = ($tm === 'other' && $to) ? $to : ($title_map[$tm] ?? '');
        $display = trim(($tl ? $tl . ' ' : '') . $fn . ' ' . $ln);
        $results[] = ['id' => $p->ID, 'name' => $display, 'url' => get_permalink($p->ID)];
    }
    wp_send_json($results);
});

// Enqueue the mention script in the Elementor editor panel.
add_action('elementor/editor/before_enqueue_scripts', function() {
    wp_enqueue_script('haifa-staff-mention', HAIFA_STAFF_V2_PLUGIN_URL . 'assets/staff-mention.js', ['jquery'], HAIFA_STAFF_V2_VERSION, true);
    wp_localize_script('haifa-staff-mention', 'haifaStaffMention', [
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'nonce'   => wp_create_nonce('haifa_staff_mention'),
    ]);
    wp_enqueue_script('haifa-staff-remote-picker', HAIFA_STAFF_V2_PLUGIN_URL . 'assets/staff-remote-picker.js', ['jquery'], HAIFA_STAFF_V2_VERSION, true);
});

// [staff_link id="42"]Name[/staff_link]
// Renders a permalink to a staff profile. Used by the @mention system so links
// survive future slug changes (ID-based, not slug-based).
add_shortcode('staff_link', function($atts, $content) {
    $atts = shortcode_atts(['id' => 0], $atts);
    $id   = absint($atts['id']);
    if (!$id) return esc_html($content);
    $url = get_permalink($id);
    if (!$url) return esc_html($content);
    return '<a href="' . esc_url($url) . '">' . esc_html($content) . '</a>';
});

// ── [acf_label] shortcode override ───────────────────────────────────────────
// Supports old Elementor templates that use [acf_label] for academic_degree_main,
// academic_degree_other, and position without requiring template changes.
// Priority 20 — runs after ACF registers its own shortcode.

add_action('init', function() {
    $handled_fields = ['academic_degree_main', 'academic_degree_other', 'position'];
    $degree_labels  = [
        'professor'           => 'פרופסור מן המניין',
        'associate_professor' => 'פרופסור חבר',
        'professor_emeritus'  => 'פרופסור אמריטוס',
        'senior_lecturer'     => 'מרצה בכיר',
        'other'               => 'אחר',
    ];

    global $shortcode_tags;
    $original_acf_handler = $shortcode_tags['acf_label'] ?? null;

    remove_shortcode('acf_label');

    add_shortcode('acf_label', function($atts) use ($handled_fields, $degree_labels, $original_acf_handler) {
        $atts = shortcode_atts(['name' => ''], $atts);
        $name = $atts['name'];

        if (!in_array($name, $handled_fields, true)) {
            return $original_acf_handler ? call_user_func($original_acf_handler, $atts) : '';
        }

        $post_id = get_the_ID();
        if (!$post_id) return '';

        if ($name === 'academic_degree_main') {
            $value = get_post_meta($post_id, 'academic_degree_main', true);
            return $degree_labels[$value] ?? '';
        }
        if ($name === 'academic_degree_other') {
            $degree = get_post_meta($post_id, 'academic_degree_main', true);
            if ($degree !== 'other') return '';
            return esc_html(get_post_meta($post_id, 'academic_degree_other', true));
        }
        if ($name === 'position') {
            return esc_html(get_post_meta($post_id, 'position', true));
        }
        return '';
    });
}, 20);

// ── v1 title_main key fix (frontend) ─────────────────────────────────────────
// Some v1 Elementor templates rendered title_main keys directly as class names
// on <span> elements. This script replaces raw key text with proper Hebrew labels.

add_action('wp_footer', function() {
    ?>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var map = {
            'professor':           'מר',
            'associate_professor': "גב'",
            'assistant_professor': 'ד"ר',
            'lecturer':            "פרופ'"
        };
        Object.keys(map).forEach(function(cls) {
            document.querySelectorAll('span.' + cls).forEach(function(el) {
                el.textContent = map[cls];
            });
        });
    });
    </script>
    <?php
});
